### ISSUE TITLE
Can it load/save?

### ISSUE THREAD

**Issue by xmontero** [floooh/docker-c64#2]
Wow! I found this docker image today. Ideal for letting kids to "play around" with peeks and pokes and learn low level stuff.

I wonder if the docker is prepared to facilitate the emulator load and save files as if we were savin/loading to a cassette tape.

So if a kid makes a `10 PRINT "hello"`+ `20 GOTO 10`, can he save this program for later use?

**Comment by floooh** [comment]
No unfortunately that's not possible, there's no connection to the filesystem. The non-docker-version (e.g. here: https://floooh.github.io/tiny8bit/) can load certain file types, but not save anything back to the filesystem.
